In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import torchvision as tv
import torchvision.transforms as transforms

In [2]:
x=torch.tensor(([1.0,2.0,3.0],[3.0,4.0,5.0]),dtype=torch.float)

In [3]:
x.size()

torch.Size([2, 3])

In [4]:
a=np.array([1,2,3])
b=torch.from_numpy(a)
print(b)

tensor([1, 2, 3])


In [5]:
#Add Tensor
y=torch.rand(2,3)
print(y.size())

torch.Size([2, 3])


In [6]:
add_tensor=torch.add(x,y)
print(add_tensor)

tensor([[1.0527, 2.0747, 3.3050],
        [3.9858, 4.9667, 5.0517]])


In [7]:
z=x+y
z

tensor([[1.0527, 2.0747, 3.3050],
        [3.9858, 4.9667, 5.0517]])

In [8]:
x1=torch.tensor(([1.0,2.0,3.0],[3.0,4.0,5.0]),dtype=torch.float)
z1=x1.view(-1,2)
z1

tensor([[1., 2.],
        [3., 3.],
        [4., 5.]])

In [9]:
transform=transforms.Compose([tv.transforms.ToTensor(),tv.transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])

In [10]:
trainset = tv.datasets.CIFAR10(root='/Users/chetanseth/Documents/OneDrive/pytorch_vipul',train=True,transform=transform,download=False)

In [ ]:
dataloader = torch.utils.data.DataLoader(trainset,batch_size=4,num_workers=4)

In [1]:
import jovian

<IPython.core.display.Javascript object>

In [5]:
jovian.commit(nb_filename='Classnotes.ipynb')

[jovian] Saving notebook..


<IPython.core.display.Javascript object>

Exception: Failed to retrieve metadata for notebook "7534439fb3b64de286a645ae5ebb0df6": (HTTP 404) {"errors":[{"code":404,"message":"Gist version not found"}],"success":false}
